const PopularProducts = [
	{
		uniqueKey: '1',
		name: 'Chicken Nuggets',
		category: 'Poultry',
		price: '1',
		unit: 'kg',
		quantity: '1',
		status: 'to buy',
	},
	{
		uniqueKey: '2',
		name: 'Salmon',
		category: 'Fish',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
		status: 'to buy',
	},
	{
		uniqueKey: '3',
		name: 'Ribeye',
		category: 'Beef',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '4',
		name: 'Tomatoes',
		category: 'Vegetables',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '5',
		name: 'Fillet',
		category: 'Beef',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '6',
		name: 'Meagre',
		category: 'Fish',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '11',
		name: 'Chicken',
		category: 'Poultry',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '21',
		name: 'Salmon',
		category: 'Fish',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '31',
		name: 'Ribeye',
		category: 'Beef',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '41',
		name: 'Tomatoes',
		category: 'Vegetables',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '51',
		name: 'Fillet',
		category: 'Beef',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '61',
		name: 'Meagre',
		category: 'Fish',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '112',
		name: 'Chicken',
		category: 'Poultry',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '212',
		name: 'Salmon',
		category: 'Fish',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '312',
		name: 'Ribeye',
		category: 'Beef',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '412',
		name: 'Tomatoes',
		category: 'Vegetables',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '512',
		name: 'Fillet',
		category: 'Beef',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
	{
		uniqueKey: '612',
		name: 'Meagre',
		category: 'Fish',
		price: '',
		unit: '',
		quantity: '',
		status: 'to buy',
	},
];

export default PopularProducts;
